### ISSUE TITLE
phase 1

### ISSUE THREAD

**Issue by mirrorcult** [mirrorcult/DELTA-SECTOR#1]
## Description

- [x] branding #3 
- [ ] font
- [ ] port tiles & decals
- [x] port airlocks #6 
- [ ] port walls / windows
- [ ] port other random wallmount sprites
- [ ] parallax? from somewhere lol. maybe sojourn or eris
- [x] disable maps / jobs i wont need #4
- [x] unblue UI colors #5
- [x] dark lighting #5
- [x] fuck with chat colors and what not #5
- [ ] reverby sounds
- [ ] upstream character menu
